services:
  database:
    image: postgres
    container_name: movies_database
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=MoviesDB
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local